### ISSUE TITLE
Can't install because of compiling failure of dependencies

### ISSUE THREAD

**Issue by clawfire** [publicMindee/mindee-api-python#1]
### Prerequisites

Put an X between the brackets on this line if you have done all of the following:

* [x] Reproduced the problem or exposed a new need
* [x] Checked the github existing issues

### Description

Cannot install due to failed cascading dependencies on Big Sur

### Steps to Reproduce

1. `pip install mindee` on MacOS Big Sur

**Expected behavior:**

Install `mindee` and dependencies, especially `matplotlib`

**Actual behavior:**

Failed to compile `numpy`, a dependency of `matplotlib` on Mac Intel

**Reproduces how often:**

100%

### Versions

- MacOS Big Sur
- Python 3.9.0

### Additional Information

I checked the issues on matplotlib project and maintener rejected [the issue](https://github.com/matplotlib/matplotlib/issues/19000) reported 3 days ago saying basicly "not my problem if you're using arm" except ... it's not an ARM issue :/

**Comment by clawfire** [comment]
the weird thing is, installing `numpy` with a `pip install numpy` work quite well.

**Comment by clawfire** [comment]
Ok so numpy use [Accelerate](https://developer.apple.com/documentation/accelerate) but seems to use deprecated methos of it which just completly crash at the building stage:
>  RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.

However, installing it with homebrew (`brew install numpy') then running a `pip install matplotlib`, and then a `pip install mindee` works.

**Comment by clawfire** [comment]
Ok now it's `PyMuPDF` which fail to build

**Comment by thentgesMindee** [comment]
Hi @clawfire, Thanks for reporting this issue.
Your last error failing to install PyMuPDF may be caused by your current pip version, it requires pip to be at least version 20.1.
Can you try upgrading pip `pip install pip --upgrade` ?

**Comment by clawfire** [comment]
> pip --version
pip 20.2.4 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)

**Comment by thentgesMindee** [comment]
It may be because PyMuPDF doesn't have a wheel yet for mac os Big Sur
(cannot find any macosx_11 here: https://pypi.org/project/PyMuPDF/#files)
You could try to install PyMuPDF using brew again

**Comment by clawfire** [comment]
Hum. There's no formula for PyMyPDF, would have to compile it myself I fear.

**Comment by thentgesMindee** [comment]
Here is the formula for mupdf https://formulae.brew.sh/formula/mupdf which should be enough for installing PyMuPDF from pip afterwards

**Comment by clawfire** [comment]
I tried it, but still have the issue with `fitz` lib. 

```
Collecting PyMuPDF
  Using cached PyMuPDF-1.18.4.tar.gz (250 kB)
Building wheels for collected packages: PyMuPDF
  Building wheel for PyMuPDF (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xj/n8nyq9dn0qjcrthjz3c808lm0000gn/T/pip-install-rna2vwhf/pymupdf/setup.py'"'"'; __file__='"'"'/private/var/folders/xj/n8nyq9dn0qjcrthjz3c808lm0000gn/T/pip-install-rna2vwhf/pymupdf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/xj/n8nyq9dn0qjcrthjz3c808lm0000gn/T/pip-wheel-ui31jcwk
       cwd: /private/var/folders/xj/n8nyq9dn0qjcrthjz3c808lm0000gn/T/pip-install-rna2vwhf/pymupdf/
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11.0-x86_64-3.9
  creating build/lib.macosx-11.0-x86_64-3.9/fitz
  copying fitz/__init__.py -> build/lib.macosx-11.0-x86_64-3.9/fitz
  copying fitz/fitz.py -> build/lib.macosx-11.0-x86_64-3.9/fitz
  copying fitz/utils.py -> build/lib.macosx-11.0-x86_64-3.9/fitz
  copying fitz/__main__.py -> build/lib.macosx-11.0-x86_64-3.9/fitz
  running build_ext
  building 'fitz._fitz' extension
  creating build/temp.macosx-11.0-x86_64-3.9
  creating build/temp.macosx-11.0-x86_64-3.9/fitz
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -arch x86_64 -I/usr/local/include/mupdf -I/usr/local/include -Imupdf/thirdparty/freetype/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c fitz/fitz_wrap.c -o build/temp.macosx-11.0-x86_64-3.9/fitz/fitz_wrap.o
  fitz/fitz_wrap.c:2738:10: fatal error: 'ft2build.h' file not found
  #include <ft2build.h>
           ^~~~~~~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for PyMuPDF
  Running setup.py clean for PyMuPDF
Failed to build PyMuPDF
Installing collected packages: PyMuPDF
    Running setup.py install for PyMuPDF ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xj/n8nyq9dn0qjcrthjz3c808lm0000gn/T/pip-install-rna2vwhf/pymupdf/setup.py'"'"'; __file__='"'"'/private/var/folders/xj/n8nyq9dn0qjcrthjz3c808lm0000gn/T/pip-install-rna2vwhf/pymupdf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xj/n8nyq9dn0qjcrthjz3c808lm0000gn/T/pip-record-l1x5oopt/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/PyMuPDF
         cwd: /private/var/folders/xj/n8nyq9dn0qjcrthjz3c808lm0000gn/T/pip-install-rna2vwhf/pymupdf/
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-11.0-x86_64-3.9
    creating build/lib.macosx-11.0-x86_64-3.9/fitz
    copying fitz/__init__.py -> build/lib.macosx-11.0-x86_64-3.9/fitz
    copying fitz/fitz.py -> build/lib.macosx-11.0-x86_64-3.9/fitz
    copying fitz/utils.py -> build/lib.macosx-11.0-x86_64-3.9/fitz
    copying fitz/__main__.py -> build/lib.macosx-11.0-x86_64-3.9/fitz
    running build_ext
    building 'fitz._fitz' extension
    creating build/temp.macosx-11.0-x86_64-3.9
    creating build/temp.macosx-11.0-x86_64-3.9/fitz
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -arch x86_64 -I/usr/local/include/mupdf -I/usr/local/include -Imupdf/thirdparty/freetype/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c fitz/fitz_wrap.c -o build/temp.macosx-11.0-x86_64-3.9/fitz/fitz_wrap.o
    fitz/fitz_wrap.c:2738:10: fatal error: 'ft2build.h' file not found
    #include <ft2build.h>
             ^~~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xj/n8nyq9dn0qjcrthjz3c808lm0000gn/T/pip-install-rna2vwhf/pymupdf/setup.py'"'"'; __file__='"'"'/private/var/folders/xj/n8nyq9dn0qjcrthjz3c808lm0000gn/T/pip-install-rna2vwhf/pymupdf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xj/n8nyq9dn0qjcrthjz3c808lm0000gn/T/pip-record-l1x5oopt/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/PyMuPDF Check the logs for full command output.
```

**Comment by olivmindee** [comment]
@clawfire According to PyMuPDF documentation, it seems that you need to use a version of Python that is no later than 3.7 to proceed with build. Also it may be simply incompatible with the new MacOS 11. This is possible that the library `freetype` is missing or not located at the same place than on previous OS version. Please check [this URL](https://stackoverflow.com/questions/14013474/lion-osx-how-to-install-libfreetype-6-dylib) about the freetype lib missing on Mac OSX.

As a general thought, we never tested the package with a MacOS11 and/or ARM CPU archi + Python 3.9 (These are new software/hardware released few weeks/days ago.) You may want to  open a ticket issue on the [PyMuPDF GitHub](https://github.com/pymupdf/PyMuPDF/issues) and check it is possible to build their package, they are usually very fast to respond! We will monitor the situation given Python 3.9 has just been released and may trigger incompatibilities. For the record, the `mindee` package is supposed to work up until Python 3.8.

Please let us know if you succeed in your installation with MacOS11!

**Comment by clawfire** [comment]
Unfortunatly using `pyenv` to install a previous version of python didn't work. 
But I could play with homebrew links for that. 
`brew install python@3.8 && brew unlink python@3.9 && brew link python@3.8`

now trying to install again `pip install mindee`. Still have the original issues. Digging a bit further
